### ISSUE TITLE
win10系统，设置为深色模式，文件夹字体颜色错误，竟然是黑色

### ISSUE THREAD

**Issue by yuexue0** [indiff/qttabbar#229]
**描述这个Bug**
win10系统，设置为深色模式，文件夹字体颜色错误，竟然是黑色
标签也是错位有问题，见图

**期望的结构**
在深色模式下，文件夹字体颜色白色，或者浅颜色

**截图**
![image](https://user-images.githubusercontent.com/11746809/175748997-1628b52c-b070-46c0-bc25-967f7b364422.png)

![image](https://user-images.githubusercontent.com/11746809/175748937-592cd075-c330-4639-a754-e59852c4812e.png)

**系统环境:**
 - 操作系统: win10

**Comment by upupoo18** [comment]
同样的问题，字和背景的颜色混在了一起，不知道怎么调整

**Comment by Bobbsterman** [comment]
I don't speak mandarin, sorry, but this can be fixed with a [dark theme](https://github.com/indiff/qttabbar/issues/189).

Unfortunately there is no option in Qttabbar to switch theme when Windows switches theme. Ideally it would!

@indiff if it helps, the relevant registry keys are here:
**Computer\HKEY_CURRENT_USER\SOFTWARE\Microsoft\Windows\CurrentVersion\Themes\Personalize**

Specifically:
**AppsUseLightTheme**
0 = dark theme
1= light theme

**Comment by indiff** [comment]
新版已经自适配，还未发布

**Comment by Bobbsterman** [comment]
> 新版已经自适配，还未发布

Thank you!
